add_newline = true

format = """
[ ](#ffffff)$directory
$character
"""

[directory]
style = "#ffffff"
truncation_length = 3
truncate_to_repo = false

[character]
success_symbol = "[❯](#ffffff)"
error_symbol = "[❯](red)"
